scverse/squidpy

- README.rst
- docs/source/index.rst
- docs/source/latest_additions.rst
- docs/source/release_notes.rst
Fixes some minor isues in the README.rst/index.rst
...
...
> Fix notebooks CI label, move latest additions

- .github/workflows/ci.yml
- .mypy.ini
- .pre-commit-config.yaml
- requirements.txt
- squidpy/_utils.py
- squidpy/gr/_build.py
- squidpy/gr/_ligrec.py
- squidpy/gr/_ppatterns.py
- squidpy/gr/_utils.py
- squidpy/im/_container.py
- squidpy/im/_feature_mixin.py
- squidpy/im/_segment.py
- squidpy/im/_utils.py
- squidpy/pl/_graph.py
- squidpy/pl/_interactive/_controller.py
- squidpy/pl/_interactive/_model.py
- squidpy/pl/_interactive/_utils.py
- squidpy/pl/_utils.py
Fixes mypy and dense `np.outer` when building `spatial_graph` using spectral transform.
...
closes #274
> Address mypy

- squidpy/datasets/_dataset.py
- squidpy/datasets/_image.py
closes #275 and add public links
> public datasets link

- .github/workflows/ci.yml
Fixes not using a token for notebooks repo dispatch.
...
...
> [ci skip] Add notebooks access token

- README.rst
- docs/source/index.rst
changed few formulations in the README
> formulation suggestions

- MANIFEST.in
- README.rst
- docs/source/index.rst
Removes useless stuff from MANIFEST.in (resulting in smaller source dist), fixes link to CONTRIBUTING.rst in `docs/source/index.rst` mentioned in #287 
...
...
> Update MANIFEST.in, fix contributing guide link

- README.rst
- docs/source/examples.rst
- docs/source/installation.rst
- docs/source/release_notes.rst
Add `pip install 'squidpy[all]'` to installation instructions.
...
...
> [ci skip] Update installation instructions

- docs/source/_ext/edit_on_github.py
- docs/source/conf.py
- squidpy/im/_feature_mixin.py
> remove `githup_repo` arg from conf sphinx

- .github/workflows/ci.yml
- docs/requirements.txt
- docs/source/conf.py
- tox.ini
Add Python3.9 testing.
No.
closes #299
> Add 3.9 job

- squidpy/gr/_ligrec.py
Fixes stripping of `COMPLEX:` in ligrec.
...
partially addresses #308
> Fix replace complex

- docs/source/conf.py
- squidpy/gr/__init__.py
- squidpy/gr/_build.py
- tests/graph/test_spatial_connectivity.py
This PR adds the commutation of the Dealunay Triangulation graph form the ``scipy.spatial`` implementation. The graph is stored a adjacency matrix, similar to ``build_connectivities`` in ``_build.py`` 
- ToDo -
Related to #314
> Delaunay graph computation

- docs/source/api.rst
- squidpy/datasets/_dataset.py
> new datasets

- squidpy/pl/_graph.py
> fix ripley plot

- squidpy/datasets/_dataset.py
> modify datasets

- squidpy/im/_container.py
- squidpy/im/_feature_mixin.py
- squidpy/im/_process.py
- squidpy/pl/_interactive/_model.py
- tests/image/test_features.py
enable passing additional layers to custom feature extractor. This is e.g. needed to the MIBI-TOF tutorial (https://github.com/theislab/squidpy_notebooks/blob/imagecontainer/tutorials/tutorial_mibitof.py)
An example of this look like the following:
```python
sq.im.calculate_image_features(
adata,
img,
library_id="library_id",
features="custom",
spot_scale=10,
layer="segmentation",
features_kwargs={"custom": {"func": segmentation_image_intensity, "additional_layers": ["image_cmyk"]}}
)
```
where `segmentation_image_intensity` is my custom feature extraction function with signature: `def segmentation_image_intensity(arr, image_cmyk)`.
I'm calling this argument ``additional_layers`` for now, not sure if this is the best name. Suggestions welcome!
- bugfix in processing
- bugfix in feature …
> Img custom features

- .github/workflows/ci.yml
- docs/source/_ext/edit_on_github.py
- docs/source/conf.py
- docs/source/utils.py
Allow pulling notebooks from `squidpy_notebooks@dev`.
Repo dispatch not yet implemented, will do slightly before new release.
N/A
...
> Allow dev notebooks

- README.rst
Fix image rendering in README.rst
N/A
N/A
> Fix readme images

- README.rst
- docs/source/conf.py
- docs/source/installation.rst
- setup.py
- squidpy/datasets/_dataset.py
- tox.ini
Fix shape of `squidpy.datasets.mibitof`, remove `astropy` and `'all'` extras.
N/A
N/A
> Fix mibitof dataset, remove astropy

- squidpy/pl/_interactive/_controller.py
- squidpy/pl/_interactive/interactive.py
exposes `canvas_only` argument in `img.interactive()` method
...
...
very minor addition but required for an improved napari tutorial
> expose canvas_only arg

- README.rst
- docs/requirements.txt
- docs/source/_ext/edit_on_github.py
- docs/source/_static/css/custom.css
- docs/source/conf.py
- docs/source/examples.rst
- docs/source/index.rst
- docs/source/latest_additions.rst
- docs/source/references.bib
- docs/source/release_notes.rst
- docs/source/spelling_wordlist.txt
- docs/source/utils.py
- setup.py
- squidpy/pl/_interactive/_utils.py
Prepare dev for new RTFD layout (stable/latest).
N/A
...
TODO:
- check docs
- write release notes
> Prepare dev

- README.rst
- docs/source/_static/css/custom.css
- docs/source/api.rst
- docs/source/classes.rst
- docs/source/conf.py
- docs/source/index.rst
- docs/source/installation.rst
- docs/source/latest_additions.rst
- docs/source/references.bib
- setup.py
- squidpy/pl/_interactive/_controller.py
Prepare patch release so that we can have stable/latest docs.
N/A
N/A
TODOs:
- merge prepare dev #365 
- revert master to `5a53dfd299fcde82ea74fea05a1a7f9ae8a30c12` (just before moran from scanpy)
- enable stable on RTFD
- change latest -> stable in `squidpy` and `squidpy_notebboks` GH
- make new release (1.0.1)
> Patch release preparation

- docs/source/conf.py
- docs/source/references.bib
- docs/source/tutorials.rst
> new tutorial layout

- squidpy/gr/_ligrec.py
- squidpy/gr/_utils.py
- tests/graph/test_ligrec.py
Allow to take symbols from a column in ``adata.var``. Note that in case there are duplicates, they are still afterwards removed (as before). The parameter is `gene_symbols: Optional[str]`.
1 new parametrized test.
closes #291
> Ligrec genenames

- .github/workflows/ci.yml
- .github/workflows/news.yml
> Fix pandoc

- docs/source/conf.py
> Fix too shallow git when generating news

- requirements.txt
Require `numba>=0.52.0`.
N/A
closes #419
> Require numba>=0.52.0

- squidpy/__init__.py
Add ``squidpy.__full_version__``.
N/A
N/A
briefly discussed in #443
> Add squidpy.__full_version__

- squidpy/gr/_ligrec.py
Finally fixes ``squidpy.gr.ligrec`` ``None`` values.
N/A (there's already a test present).
handles #443
> Explicitly check for None in complex policy

- README.rst
- README_pypi.rst
- docs/source/index.rst
The grammar for the napari bullet is a bit off. I think this will make more sense.
> Fix grammar in docs

- setup.py
- squidpy/im/_segment.py
- squidpy/pl/_interactive/_controller.py
Do not set edge with in :mod:`napari` since it caused all points to be black.
N/A
closes #486
> Fix/napari 0.4.15

- squidpy/im/_container.py
- tests/image/test_container.py
Add singleton Z-dim when loading from *Zarr* and not present.
1 new test.
further addresses #507
> Fix missing Z-dim

- squidpy/gr/_build.py
Add a warning to clarify the usage of :func:`squidpy.gr.spatial_neighbors`.
#498
> Add warning to clarify usage of `spatial_neighbors`

- tests/datasets/test_dataset.py
- tests/datasets/test_download_visium_dataset.py
- tox.ini
> skip test download

- squidpy/pl/_spatial.py
- squidpy/pl/_spatial_utils.py
Allow for passing channels explicitly, remove restriction of `max(channel) < 3`.
N/A
N/A
> Generalize img_channel in plotting

- squidpy/im/_container.py
- squidpy/pl/_interactive/_model.py
Refactor :meth:`squidpy.im.ImageContainer.subset` to return a view.
No tests, in light of #429 
closes #530
> Refactor subsetting

- .github/.codecov.yml
- .github/workflows/deployment.yml
- .github/workflows/news.yml
- .github/workflows/test.yml
- CONTRIBUTING.rst
- README.rst
- README_pypi.rst
- docs/source/conf.py
- docs/source/index.rst
- docs/source/installation.rst
- docs/source/release/changelog/546.bugfix.rst
- docs/source/release/changelog/547.bugfix.rst
- docs/source/release/changelog/548.bugfix.rst
- docs/source/release/notes-dev.rst
- docs/source/spelling_wordlist.txt
- docs/source/utils.py
- tox.ini
Rename default branch from ``master`` to ``main``.
> rename master to main

- .pre-commit-config.yaml
- docs/source/_ext/typed_returns.py
- docs/source/create_news_fragment.py
- docs/source/utils.py
- squidpy/_constants/_utils.py
- squidpy/datasets/_utils.py
- squidpy/gr/_build.py
- squidpy/gr/_ligrec.py
- squidpy/gr/_ppatterns.py
- squidpy/im/_feature_mixin.py
- squidpy/pl/_interactive/_widgets.py
- squidpy/pl/_spatial.py
- squidpy/pl/_spatial_utils.py
- squidpy/pl/_utils.py
- squidpy/read/_utils.py
- tests/conftest.py
- tests/graph/test_ligrec.py
- tests/graph/test_spatial_neighbors.py
- tests/image/test_container.py
- tests/image/test_features.py
- tests/image/test_io.py
- tests/image/test_processing.py
- tests/image/test_segmentation.py
- tests/plotting/test_interactive.py
> fix typing Type

- squidpy/pl/_color_utils.py
Better error message for handling palette in  :func:`squidpy.pl.spatial_scatter`.
> better error message for palette

- docs/source/release/changelog/568.bugfix.rst
- docs/source/release/changelog/569.doc.rst
- docs/source/release/notes-1.2.2.rst
- docs/source/release/notes-dev.rst
> fix release notes

- squidpy/read/_read.py
Fixes :func:`squidpy.read.nanostring` . Closes #566 .
> fix nanostring fov file

- .github/workflows/test.yml
- docs/requirements.txt
> update requirements in docs

- docs/source/conf.py
- docs/source/spelling_wordlist.txt
- docs/source/tutorials.rst
New tutorial for 10x Genomics Xenium data.
Tested on two data sets
> updated tutorials.rst

- README.rst
- docs/source/index.rst
- tox.ini
Fix CI badges and tox.
N/A
N/A
> Fix badges

- .github/workflows/release.yml
> add missing step

- docs/release/notes-1.3.0.rst
- Fixed date 2022 -> 2023
- Added '#' to a PR link
> Fix v1.3.0 release notes

- README.rst
Add NumFOCUS logo and text on README file.
> Add num focus logo and text 

- pyproject.toml
> fix napari install

- .cruft.json
- .pre-commit-config.yaml
- docs/conf.py
- docs/release/notes-1.4.2.rst
- docs/release/notes-dev.rst
> update releases and precommit

- .github/workflows/test.yml
- .pre-commit-config.yaml
- src/squidpy/gr/_sepal.py
- src/squidpy/pl/_var_by_distance.py
- tests/graph/test_spatial_neighbors.py
- tests/graph/test_utils.py
- tests/image/test_container.py
> fix precommit and add pre-release test

- docs/release/notes-1.6.1.rst
> add release note

- src/squidpy/pl/_var_by_distance.py
- src/squidpy/tl/_var_by_distance.py
- Fixes `tl.var_by_distance()` behaviour if numpy arrays of coordinates are passed as anchor point.
- Updates `pl.var_by_distance()` to plot multiple variables on a single plot.
> Update var_by_distance functionalities

- docs/release/notes-1.6.1.rst
- docs/release/notes-1.6.2.rst
- docs/release/notes-dev.rst
Updated release notes for v1.6.1, added release notes for v.1.6.2 and updated dev notes.
> Update release notes

- .github/workflows/release.yml
> Updated token name

- LICENSE
> (chore): update license copyright

- .editorconfig
- .github/.codecov.yml
- .github/release.yml
- .github/workflows/build.yml
- .github/workflows/deployment.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- .pre-commit-config.yaml
- .readthedocs.yml
- pyproject.toml
Using 4 with prettier is not compatible how `-` lists work, which leads to weird indenting that isn’t a multiple of 4 and is therefore hard to edit.
> chore: fix messed-up yaml formatting

- src/squidpy/gr/__init__.py
- src/squidpy/gr/_build.py
- src/squidpy/gr/_nhood.py
- src/squidpy/im/_io.py
- tests/graph/test_nhood.py
- tests/graph/test_spatial_neighbors.py
Fixes https://github.com/scverse/squidpy/issues/1038
> Replacing fixed size tuples as return types
