- squidpy/im/_container.py
- tests/image/test_container.py
Delegate `del` in ImageContainer.
1 new test for the deletion.
closes #285 
In the future, we should consider using a descriptor to delegate other `xarray.Dataset` methods/attributes.
> Delegate del

- squidpy/im/_container.py
- squidpy/pl/_interactive/_controller.py
- squidpy/pl/_interactive/_model.py
- fix missing library id when rescaling image crops
- fix wrong spot_diameter in napari. There was a bug in the code that lead to napari only working with 2 library_ids. 
...
...
> Fix napari for multiple library_ids

- docs/source/api.rst
- docs/source/classes.rst
- squidpy/pl/_interactive/_widgets.py
Change how classes are displayed in the docs. Add an overview table for each class. Resulting docs:
￼
Remaining issue (not sure how to solve): Long names in the sidebar. I tried to remove the prefix by adding `add_module_names=False` in the config, but that did not seem to have an effect.
￼![Pasted Graphic 2](https://user-images.githubusercontent.com/13350159/124102121-5e600a00-da60-11eb-9cd2-55cdf7b5598b.png)
...
...
> add classes overview for each class

- .bumpversion.cfg
- setup.py
- squidpy/__init__.py
- squidpy/gr/_build.py
In the computation of the spatial graph from the Delaunay triangulation, the code to obtain the list of rows and columns is unnecessary given that they are already computed by `scipy.spatial.Delaunay` and thus stored into `tri.vertex_neighbor_vertices`.
The connections are already in a format suitable for the csr_matrix.
Since the building of the csr_matrix between the two methods (delaunay vs. nearest neighbor) is now different I replaced the way of setting the diagonal elements in the case of `set_diag=True` into a way that is independent of how the matrix is built.
The modification results in a speed-up of the `gr.spatial_neighbors` function from:
`928 ms ± 9.53 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)`
to
`46 ms ± 2.28 ms per loop (mean ± std. dev. of 7 runs, 10 loops …
> Delaunay optimization

- .github/workflows/ci.yml
- squidpy/im/_container.py
- squidpy/im/_io.py
- tests/image/test_container.py
- tests/image/test_io.py
Fix loading `TIFFs`: problem was that `tifffile.imread` returned `(y, x, z)`, whereas we expected `(z, y, x)` + reshape from
the former into latter caused the artifacts in #389 .
Also fixes passing explicit dimnames to 3D arrays when loading from files.
TODO: fix linting
In the future, switch to e.g. `dask_image.read` for either TIFFs only or for all image types once `pims` (backend for their IO) allows lazy loading if JPEGs.
Also, consider (in the future) refactoring our IO to some `Dimension` class (will be very useful/almost necessary) when adding new dimension to `ImageContainer`.
TODO: 2 tests 
1. one that tests setting `dims` explicitly for 3D image on disk
2. one that tries to load a `.tifffile` similar to the one in #389 
closes #389
> Fix reading tiffs

- squidpy/gr/_utils.py
`squidpy.gr._ligrec._check_tuple_needles` has an error message when invalid cluster names are passed to it through `squidpy.gr._ligrec`, which reads ""Invalid cluster `<Bad Cluster>`.", but if the invalid one is the second object of the tuple, the error message will print the first object of the tuple. This fix should give the correct error message now.
```
from itertools import product
clusters = list(map(str, adata_parent.obs["leiden_coarse"].cat.categories))
clusters.append("bad one")
clusters = list(product(clusters, repeat=2))  # type: ignore[no-redef,assignment]
clusters = sorted(
sp.gr._ligrec._check_tuple_needles(
clusters,  # type: ignore[arg-type]
adata_parent.obs["leiden_coarse"].cat.categories,
msg="Invalid cluster `{0!r}`.",
reraise=True,
)
)
```
Before: ValueError: Invalid …
> Have gr._utils._check_tuple_needles error message report correct string if invalid cluster name supplied

- .pre-commit-config.yaml
- squidpy/datasets/_dataset.pyi
- squidpy/datasets/_image.pyi
Add type stubs to datasets.
Pre-commit and test suites
Note the need to exclude original *.py files from the mypy pre-commit due to pre-commit/mirrors-mypy#33. A solution to maintain type safety would be to add a full mypy/pyright step to the CI workflow.
> Add type stubs to datasets

- squidpy/im/_container.py
Include check to be able to load ImageContainer that were generated from another version of squidpy.
Fixes loading of ImageContainer for me, see #507. 
#507
> Check dims for backwards compatibility of image loading

- squidpy/pl/_utils.py
Fix a typo when saving a figure caused a strange directory name to be created.
N/A
closes #505
> Fix typo in save_fig: Path -> path

- squidpy/_constants/_pkg_constants.py
- squidpy/im/_container.py
- squidpy/pl/_interactive/_model.py
- tests/image/test_container.py
Make `spot_diameter` more flexible, also allow to pass an additional kwarg in `generate_spot_crops`
Enable specifying diameter in :meth:`squidpy.im.ImageContainer.generate_spot_crops`.
This fixed the gerneration of image dependent on spatial coordinates in my adata, something like this: 
```python
for img, obs in image.generate_spot_crops(adata[adata.obs.id=='37_48_A1'],library_id='37_48_A1-488', return_obs=True, spot_diameter_key='spot_diameter_real'): 
plt.imshow(img['37_48_A1'].squeeze()[...,:3])
```
where 
```python
```python
>>> adata.uns['spatial']['37_48_A1-488']['spot_diameter_fullres']
{'images': {'lowres': array([[0, 0, 0, ..., 0, 0, 0],
[0, 0, 0, ..., 0, 0, 0],
[0, 0, 0, ..., 0, 0, 0],
..., …
> Make `spot_diameter` more flexible

- squidpy/_constants/_pkg_constants.py
- squidpy/im/_container.py
- squidpy/pl/_interactive/_model.py
Fix not correctly subsetting :class:`anndata.AnnData` when interactively visualizing it.
```python
import scanpy as sc
import anndata as ad
import squidpy as sq
library_ids = ["V1_Mouse_Brain_Sagittal_Posterior", "V1_Mouse_Brain_Sagittal_Posterior_Section_2"]
adatas, imgs = [], []
use_hires_tiff = False
for library_id in library_ids:
adatas.append(sc.datasets.visium_sge(library_id, include_hires_tiff=use_hires_tiff))
adatas[-1].var_names_make_unique()
adata = ad.concat(adatas, uns_merge="only", label="library_id", keys=library_ids, index_unique="-")
img = sq.im.ImageContainer.from_adata(adata, library_id='V1_Mouse_Brain_Sagittal_Posterior_Section_2')
img.interactive(adata, library_key="library_id", …
```
> Fix adata subset in ImageContainer

- squidpy/read/_read.py
- tests/read/test_visium.py
Close #536. Set consistent image resolution key in `sq.read.visium`.
> fix res_key in reader

- squidpy/read/_read.py
`sq.read.nanostring` reads only image file extensions.
> read only images of a specified format in CellComposite,CellLabels

- requirements.txt
- squidpy/pl/_ligrec.py
- squidpy/pl/_spatial_utils.py
Fix :mod:`pandas` in :func:`squidpy.pl.ligrec`.
N/A
closes #622
> Fix `squidy.pl.ligrec`'s `pandas` usage

- .github/workflows/news.yml
- docs/source/conf.py
- squidpy/pl/_graph.py
- squidpy/pl/_utils.py
- tests/plotting/test_image.py
- tox.ini
Fix :func:`squidpy.pl.extract` on views.
1 modified test.
closes #646
> Fix `squidpy.pl.extract` on views

- squidpy/read/_read.py
Set coordinates' index type to same as in :attr:`anndata.AnnData.obs` in :func:`squidpy.read.vizgen` and :func:`squidpy.read.visium`.
No new tests.
closes #657
> Set index's dtype ib `sq.read.vizgen`/`sq.read.visium`

- .github/workflows/test.yml
- .pre-commit-config.yaml
- docs/source/tutorials.rst
- docs/source/utils.py
- requirements.txt
- squidpy/pl/_ligrec.py
- tests/graph/test_ligrec.py
- tests/image/test_container.py
- tests/plotting/test_graph.py
Minor fix for tests and update of requirements.
> Update reqs and tests

- squidpy/read/_read.py
In the latest MERFISH public data, the cell_metadata index is recognized as an integer, which requires conversion to a string format.  This commit adds a function to convert the index to a string, ensuring compatibility with downstream applications.
When attempting to load the latest public data from https://vizgen.com/data-release-program/, specifically the FFPE_Human_Immuno_oncology dataset, I have encountered an issue where the 'obs' of the Anndata object is filled with NaN values. This issue is caused by the presence of different index types between 'adata.obs' and 'coords', which leads to errors when merging them.
I have found that this issue can be resolved by setting the data type of 'coords' as 'str'. After making this adjustment, the 'obs' of the Anndata object is populated with …
> Convert cell_metadata index from integer to string for latest MERFISH public data

- src/squidpy/read/_read.py
Changed the column heading of the `transformation_matrix` in the `uns` slot from `int64` to `str` when `transformation_file` is read in. This is so resulting `adata` can be written out as h5ad file.
Download public vizgen data then run the following:
```
from pathlib import Path
import scanpy as sc
import squidpy as sq
vizgen_dir = Path().resolve() / "HumanBreastCancerPatient1"
adata_bk = sq.read.vizgen(
path=vizgen_dir,
counts_file="cell_by_gene.csv",
meta_file="cell_metadata.csv",
transformation_file="micron_to_mosaic_pixel_transform.csv",
)
adata_bk.write("test.h5ad")
```
`closes #727 `
> change transformation_matrix column type to str

- src/squidpy/tl/_var_by_distance.py
Test for tl._var_by_dist.py fails if more than one anchor point is used, since the indices of the df no longer match those of .obs
By comparing assertion result of previous code with result after reindexing
> Fix var_by_distance to pass test after pandas update

- docs/api.rst
- docs/conf.py
- docs/release/notes-dev.rst
- pyproject.toml
- src/squidpy/gr/__init__.py
- src/squidpy/gr/_build.py
- tests/conftest.py
- tests/graph/test_spatial_neighbors.py
This PR introduces two features:
- compute spatial graph based on regions (shapes, labels) from spatialdata.
- mask the graph base on a shapes element (in spatialdata)
The idea is, given a graph and a polygon, mask it base on the polygon (either every edge contained inside the polygon, or everything that is outside or partially outside to the polygon). 
e.g. see
**Original**
**Positive mask**
**Negative mask**
It would be nice to have feedback on argument names/apis and I should also be adding an example to show how to use it.
> compute graph base on spatialdata regions and add mask graph based on polygon

- pyproject.toml
The latest version of xarray directly includes `DataTree` but with a datamodel that is different from before. Since the xarray version was not constraint in `SpatialData` this led to errors. The current latest version of `SpatialData` constraints the xarray version used until the latest version of xarray is supported.
local tests
> Update spatialdata dependency

- .github/ISSUE_TEMPLATE/question.md
You've already removed Mike but forgot about this one @timtreis 
See internal Slack discussion
> Remove Gio from being autoassigned to questions

- pyproject.toml
See #933: `zarr` needs to be upper bounded as other dependencies cannot use `zarr` `v3` yet see e.g., https://github.com/scverse/anndata/issues/1817
N/A
Fixes  #933
> (fix): upper bound `zarr`

- docs/conf.py
Every now and then CI/CD fails because sphinx can't reach links in time, f.e. [here](https://github.com/scverse/squidpy/actions/runs/13334734059/job/37247296268). Increased timelimit to hopefully avoid that.
> Updated linkcheck times for sphinx

- tox.ini
A mismatch between the environment names defined in [gh-actions] (e.g. py3.10) and those in [tox] envlist (e.g. py310) caused tests to fail because the correct tox environment could not be found. Renaming the envlist to match the factors (e.g. py3.10-linux → py310-linux or vice versa) fixed the issue.
> Fixed error in tox.ini

- .scripts/ci/download_data.py
- src/squidpy/datasets/_10x_datasets.py
- src/squidpy/datasets/__init__.py
- src/squidpy/datasets/_dataset.py
- src/squidpy/datasets/_utils.py
- tests/datasets/test_download_visium_dataset.py
- tests/image/test_io.py
- tox.ini
The `squidpy.datasets` function were downloading AnnDatas or ImageContainers. For a lot of work, I'd love to have an easy SpatialData download. So here it is. Data was created as described here: https://github.com/scverse/spatialdata-notebooks/pull/131
Edit: I had to write some quite hacky code around the download function to also have it be automatically downloaded during CI/CD. Theoretically, that entire part should be refactored because it's (unnecessarily complicated)**3, but time yada yada
> Added function to download Visium as SpatialData

- .github/release.yml
- .github/workflows/release.yml
To simplify maintenance, we're now doing the same release process as SpatialData
> Mirror `SpatialData` release action

- .pre-commit-config.yaml
- src/squidpy/read/_utils.py
Fixes
```
/home/lukas/miniforge3/envs/lamindb/lib/python3.12/site-packages/anndata/utils.py:429: FutureWarning: Importing read_text from `anndata` is deprecated. Import anndata.io.read_text instead.
warnings.warn(msg, FutureWarning)
```
> Fix IO warning

- src/squidpy/_docs.py
- src/squidpy/_utils.py
Related: https://github.com/scverse/squidpy/issues/957
Following the discussion in https://github.com/scverse/squidpy/pull/984#issuecomment-2783410367 I modified the docs. I also wrote that this argument will be removed in the future based on our conversations but I am not sure about that.
If that is correct I will create an issue titled: `Reconsidering usage of paralellize` or something like that
> Docs: Edit the argument documentation of `n_jobs` of the `parallelize` function

- src/squidpy/gr/_ligrec.py
- tests/graph/test_ligrec.py
Fixes https://github.com/scverse/squidpy/issues/871 and https://github.com/scverse/squidpy/issues/840
When comparing version 1.2.4 and main, I noticed 0's were integers while non zeros were floats in the main branch while in the old version they were all the float. I think this caused some rounding problems and integer divisions. I have some ideas on how to expose these bugs on unit tests but I just wanted to open this PR to show the fix.
Ligrec needs two things but I seperated the other to simplify this PR. Normally we also need to modify numba code because it doesn't parallelize due to an assertion exitting the loop early. Those changes are in this branch: https://github.com/scverse/squidpy/compare/main...fix/ligrec
The notebooks are now reproducable by my local tests. We used notebook …
> Ligrec Reproducibility and Bug Fix in Sparse Data.

- pyproject.toml
Since python 3.10 is not supported by scientific-python.org/specs/spec-0000/#support-window the science community I will bump up the version. This was we can also use `fast-array-utils`
> Deprecate Python 3.10
